#!/bin/bash

PAL_LOADER=$(readlink -f ${BASH_SOURCE[0]})
PAL_DIR=$(readlink -f $(dirname $PAL_LOADER)/../../../../Pal/src)
PAL=$PAL_DIR/pal

MANIFEST=
GDB_CMD=
PAL_CMD=$PAL

if [ "$GDB" == "1" ]; then
	GDB="gdb"
fi

if [ "$GDB" != "" ] && [ "$GDB" != "0" ]; then
	GDB_CMD="$GDB --args"
fi

if [ "$SEC" == "1" ]; then
	echo "Use reference monitor"
fi

while [ "$1" != "" ];
do
	if [ "$MANIFEST" == "" ]; then
		MANIFEST=$1
		shift
		continue
	fi

	break
done

if [ ! -f "$PAL_CMD" ]; then
	echo "$PAL_CMD is not built, or security mode is not supported"
	exit 1
fi

#XXX add kernel boot options to /etc/default/grub if needed:
#
#   isolcpus=1 intel_pstate=disable
#
#VICTIM_CPU=0
#SPY_CPU=1
#CPU_MIN_FREQ=400Mhz #2.50GHz 
#CPU_MAX_FREQ=2.50GHz
#
#echo "maximally overclocking spy CPU $SPY_CPU @$CPU_MAX_FREQ"
#sudo cpufreq-set -c $SPY_CPU -f $CPU_MAX_FREQ
#echo "maximally underclocking victim CPU $VICTIM_CPU @$CPU_MIN_FREQ"
#sudo cpufreq-set -c $VICTIM_CPU -f $CPU_MIN_FREQ
#cpufreq-info

set -x
exec $GDB_CMD $PAL_CMD $MANIFEST "$@"
